sudo: required
#language: node_js
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  - openssl aes-256-cbc -K $encrypted_16f60ee10e64_key -iv $encrypted_16f60ee10e64_iv -in travis-service-account.json.enc -out travis-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-service-account.json
  - gcloud config set project udemy-k8s-266216 
  - gcloud config set compute/zone us-central1-a
  - gcloud container clusters get-credentials standard-cluster-1
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker build -t 3stark/complex-test -f ./client/Dockerfile.dev ./client

#script:
#  - docker run -e CI=true 3stark/complex-test npm run test 
  
deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: master
    
#addons:
#  apt:
#    update: true