language: node_js
sudo: required
services:
  - docker
before_install:
  - openssl aes-256-cbc -K $encrypted_16f60ee10e64_key -iv $encrypted_16f60ee10e64_iv -in travis-service-account.json.enc -out travis-service-account.json -d
  - curl https://sdk.cloud.google.com | bash > /dev/null;
  - source $HOME/google-cloud-sdk/path.bash.inc
  - gcloud components update kubectl
  - gcloud auth activate-service-account --key-file travis-service-account.json
#addons:
#  apt:
#    update: true